### ISSUE TITLE
Internal Server Error when trying to log in with Google on the Heroku example app

### ISSUE THREAD

**Issue by tadasajon** [dwyl/auth_plug_example#11]
Following the link to the example app running on Heroku: I get the landing page correctly, I click on Google to login through my google account, I choose my account, and then I get "Internal Server Error"

**Comment by tadasajon** [comment]
I was using Safari before.  GitHub auth works.  I tried again just now using Firefox and I got the same Internal Server Error when trying to log in with Google.

**Comment by nelsonic** [comment]
Updated the project to Phoenix `1.6` https://github.com/dwyl/auth_plug_example/pull/13 works as expected. 💭 
Can't replicate the Internal Server Error. But will keep trying. 👨‍💻

**Comment by tadasajon** [comment]
I just tried again from a new computer and again got the Internal Server Error. It might be helpful to look at the heroku logs.

**Comment by nelsonic** [comment]
We aren't actually logging much on Heroku ...  https://dashboard.heroku.com/apps/auth-plug-example/logs (just the default)
![image](https://user-images.githubusercontent.com/194400/136676430-aa480616-01b5-442c-888a-afcf1678a46a.png)

Avoids leaking any Personal Info or tokens, etc. 💭 

When I successfully login using my Google account in Brave with all history/session/cookies deleted:
![image](https://user-images.githubusercontent.com/194400/136676584-e5646477-219a-4fb2-a13c-91d13153b0ba.png)

These are the logs:
![image](https://user-images.githubusercontent.com/194400/136676631-d829ddc6-06c4-4204-85f6-15ccd012e4a3.png)

If you think there's anything we could log _temporarily_ to debug this, please let us know. 👍

**Comment by nelsonic** [comment]
We've updated both `auth` and `auth_plug` recently. ✅ 
Suggest re-testing this to confirm if you still see errors. 💭

**Comment by tadasajon** [comment]
> Hi @tadasajon are you still seeing the same error? I've re-deployed the app to Heroku, please refresh and confirm. Thanks.

Ok, it seems to work now.  I am first re-directed from auth-plug-example.herokuapp.com to dwylauth.herokuapp.com where I am asked to sign in with GitHub or Google.  I choose Google.  Then it takes me to a Google login screen.  Once I'm successfully past that I am taken back to auth-plug-example.herokuapp.com 

![mini 2021-10-20 at 7 44 51 PM](https://user-images.githubusercontent.com/86680401/138187579-f92998df-fd33-4e04-bd65-fbdebadd59a2.png)
![mini 2021-10-20 at 7 45 10 PM](https://user-images.githubusercontent.com/86680401/138187598-32eb13e3-d288-40a7-85df-62d80cfc59de.png)
