### ISSUE TITLE
Login automatically after logout

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth_plug_example#17]
Once you login then logout, the admin page is accessible as the auth app still think the user is still logged in.
I think this is the same issue related to https://github.com/dwyl/auth/pull/160

![image](https://user-images.githubusercontent.com/6057298/144086537-0e2d275d-5a09-47ba-b8bd-87ccc10195c8.png)

**Comment by nelsonic** [comment]
@SimonLab can you please confirm if this was with GitHub Auth? (Or Which Auth provider it was) Thanks.

**Comment by SimonLab** [comment]
Now that https://github.com/dwyl/auth/pull/160 is merged this issue is fixed.
Because the jwt session was stored on the consumer app but also on the auth app. Calling the logout endpoint was properly deleting the session on the consumer app but not on auth, so the next time the user attempted to login (with either Github Google or email), the auth app saw that the jwt was still there and logged in the user automatically back in the consumer app.

**Comment by nelsonic** [comment]
Thanks for confirming 👍
