### ISSUE TITLE
Error when trying to sign in with Github or Google Drive

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/auth_plug_example#41]
Hey there! Thank you kindly for the plug, it's mighty useful!

Unfortunately, I seem to be running into an error when trying to sign in using Github or Google.
I followed through each step exactly (with the only exception of naming the path `\auth` instead of `\admin`), inclusively creating myself an app with my own `AUTH_API_KEY` but everytime I try click to sign-in through Github...

<img width="1459" alt="Screenshot 2022-10-12 at 18 41 42" src="https://user-images.githubusercontent.com/17494745/195411665-7bc9b8aa-6b22-4d62-947a-5e461c79a486.png">

this error pops up:
```
[info] GET /auth
[debug] Processing with ChatWeb.PageController.auth/2
  Parameters: %{"jwt" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfaWQiOjg1LCJhdXRoX3Byb3ZpZGVyIjoiZ2l0aHViIiwiZW1haWwiOiJsdWNobzE0Z2FyZmllbGRAZ21haWwuY29tIiwiZ2l2ZW5OYW1lIjpudWxsLCJpZCI6MTU0LCJwaWN0dXJlIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzE3NDk0NzQ1P3Y9NCIsInJvbGVzIjoiNiw2Iiwic2lkIjozMzAsInN0YXR1cyI6MSwiYXVkIjoiSm9rZW4iLCJleHAiOjE2OTcxMzM0ODAsImlhdCI6MTY2NTU5NjQ4MCwiaXNzIjoiSm9rZW4iLCJqdGkiOiIyc2VtNmI1Y2s3NGo5aHIzZ3MwMDAwNTUiLCJuYmYiOjE2NjU1OTY0ODB9.3DMBKwoMSmP-VEZyhrFrjbvaYNJRzIRYZtWmmeO2IJk"}
  Pipelines: [:browser, :auth]
[error] :signature_error
[debug] Phoenix.Router halted in :auth/2
[info] Sent 302 in 6211ms
```

A different scenario occurs when I try to use Google Drive. It just pops up an Internal Server Error...
<img width="1840" alt="Screenshot 2022-10-12 at 18 44 21" src="https://user-images.githubusercontent.com/17494745/195412126-3868f7ec-4569-4131-981f-9eb75a9b32db.png">

I've tried debugging step-by-step but I'm still completely at a loss.

Any ideas? 🤔 

Thank you!

**Comment by nelsonic** [comment]
@LuchoTurtle please try this again but using https://auth.dwyl.com/ instead of the heroku app (which we will be deleting soon). Thanks! 👍

**Comment by nelsonic** [comment]
Ah … the URL at the end of the API key should work … what version of **auth_plug** are you using? 💭
